project:
  type: manuscript
  output-dir: _manuscript

manuscript:
  article: index.qmd

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  pdf: default

  # (other formats)
  # pdf: default

execute:
  freeze: auto



